# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ab75a9324bba81e9227044c7bb592d08eb7ececf97057d27b7f2747ee026bf8148db04fed41095404733bd0adc73c91e228bf0aeae86c2f1934ac1b02aea095

test:
  secret_key_base: ca7f36f81ec171b1616686f0487ab5967edb4736c2bf078096852e33b48bde0dd5662b51cbf0edbd9b3cb3b884b0eecd2a0bade10566045cdd7c64f2f05bbc08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
